In [1]:
#-*-coding:utf-8 -*-
import pandas as pd
import numpy as np
import sys
import tensorflow as tf

C:\Users\15412\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
df = pd.read_table(r'E:\tianchisaialibaba\zengqisai/zhengqi_train.txt')
df = pd.DataFrame(df)
df.to_csv(r'E:\tianchisaialibaba\zengqisai/zhengqi_train1.csv')


In [3]:
df =  pd.read_csv(r'E:\tianchisaialibaba\zengqisai/zhengqi_train1.csv')
df.head()

Unnamed: 0     V0     V1     V2     V3     V4     V5     V6     V7     V8  \
0           0  0.566  0.016 -0.143  0.407  0.452 -0.901 -1.812 -2.360 -0.436   
1           1  0.968  0.437  0.066  0.566  0.194 -0.893 -1.566 -2.360  0.332   
2           2  1.013  0.568  0.235  0.370  0.112 -0.797 -1.367 -2.360  0.396   
3           3  0.733  0.368  0.283  0.165  0.599 -0.679 -1.200 -2.086  0.403   
4           4  0.684  0.638  0.260  0.209  0.337 -0.454 -1.073 -2.086  0.314   

    ...      V29    V30    V31    V32    V33    V34    V35    V36    V37  \
0   ...    0.136  0.109 -0.615  0.327 -4.627 -4.789 -5.101 -2.608 -3.508   
1   ...   -0.128  0.124  0.032  0.600 -0.843  0.160  0.364 -0.335 -0.730   
2   ...   -0.009  0.361  0.277 -0.116 -0.843  0.160  0.364  0.765 -0.589   
3   ...    0.015  0.417  0.279  0.603 -0.843 -0.065  0.364  0.333 -0.112   
4   ...    0.183  1.078  0.328  0.418 -0.843 -0.215  0.364 -0.280 -0.028   

   target  
0   0.175  
1   0.676  
2   0.633  
3   0.206  
4   0.384  

[5 rows x 40 columns]

In [45]:
import matplotlib.pyplot as plt
#%matplotlib inline  

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2888 entries, 0 to 2887
Data columns (total 40 columns):
Unnamed: 0    2888 non-null int64
V0            2888 non-null float64
V1            2888 non-null float64
V2            2888 non-null float64
V3            2888 non-null float64
V4            2888 non-null float64
V5            2888 non-null float64
V6            2888 non-null float64
V7            2888 non-null float64
V8            2888 non-null float64
V9            2888 non-null float64
V10           2888 non-null float64
V11           2888 non-null float64
V12           2888 non-null float64
V13           2888 non-null float64
V14           2888 non-null float64
V15           2888 non-null float64
V16           2888 non-null float64
V17           2888 non-null float64
V18           2888 non-null float64
V19           2888 non-null float64
V20           2888 non-null float64
V21           2888 non-null float64
V22           2888 non-null float64
V23           2888 non-null flo

In [47]:
data1  = df.iloc[0:2888,1:39]
data2 = df.iloc[0:2888,39:]
data1.head()

V0     V1     V2     V3     V4     V5     V6     V7     V8     V9  \
0  0.566  0.016 -0.143  0.407  0.452 -0.901 -1.812 -2.360 -0.436 -2.114   
1  0.968  0.437  0.066  0.566  0.194 -0.893 -1.566 -2.360  0.332 -2.114   
2  1.013  0.568  0.235  0.370  0.112 -0.797 -1.367 -2.360  0.396 -2.114   
3  0.733  0.368  0.283  0.165  0.599 -0.679 -1.200 -2.086  0.403 -2.114   
4  0.684  0.638  0.260  0.209  0.337 -0.454 -1.073 -2.086  0.314 -2.114   

   ...      V28    V29    V30    V31    V32    V33    V34    V35    V36    V37  
0  ...   -0.450  0.136  0.109 -0.615  0.327 -4.627 -4.789 -5.101 -2.608 -3.508  
1  ...    0.671 -0.128  0.124  0.032  0.600 -0.843  0.160  0.364 -0.335 -0.730  
2  ...    1.287 -0.009  0.361  0.277 -0.116 -0.843  0.160  0.364  0.765 -0.589  
3  ...    1.298  0.015  0.417  0.279  0.603 -0.843 -0.065  0.364  0.333 -0.112  
4  ...    1.289  0.183  1.078  0.328  0.418 -0.843 -0.215  0.364 -0.280 -0.028  

[5 rows x 38 columns]

In [48]:
data_x = data1.values
data_y= data2.values
print(data_x)
print(data_y)

[[ 0.566  0.016 -0.143 ... -5.101 -2.608 -3.508]
 [ 0.968  0.437  0.066 ...  0.364 -0.335 -0.73 ]
 [ 1.013  0.568  0.235 ...  0.364  0.765 -0.589]
 ...
 [-0.394 -0.721 -0.485 ... -0.349  0.951  0.748]
 [-0.219 -0.282 -0.344 ... -0.23  -0.301  0.555]
 [ 0.368  0.38  -0.225 ... -0.19  -0.567  0.388]]
[[0.175]
 [0.676]
 [0.633]
 ...
 [0.005]
 [0.35 ]
 [0.417]]


In [49]:
data_x.shape[1]

38

In [152]:
train_X = data_x
train_Y = data_y

In [153]:
# Parameters
learning_rate = 0.01
training_epochs = 1000
display_step = 50
n_samples = train_X.shape[0]

In [154]:
rng = np.random
# tf Graph Input
X = tf.placeholder("float")
Y = tf.placeholder("float")

# Set model weights
#W = tf.Variable(rng.randn(), name="weight")
#b = tf.Variable(rng.randn(), name="bias")
W = tf.get_variable("W", shape=[2888, 38])
b = tf.Variable(rng.randn(), name="bias")
   
print(W)
print(b)
print(X)

<tf.Variable 'W:0' shape=(2888, 38) dtype=float32_ref>
<tf.Variable 'bias:0' shape=() dtype=float32_ref>
Tensor("Placeholder:0", dtype=float32)


In [155]:
# Construct a linear model
pred = tf.add(tf.multiply(X, W), b)

In [156]:
# Mean squared error
cost = tf.reduce_sum(tf.pow(pred-Y, 2))/(2*n_samples)
# Gradient descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [157]:
# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()

In [ ]:
# Start training
with tf.Session() as sess:
    sess.run(init)

    # Fit all training data
    for epoch in range(training_epochs):
        for (x, y) in zip(train_X, train_Y):
            sess.run(optimizer, feed_dict={X: x, Y: y})

        #Display logs per epoch step
        if (epoch+1) % display_step == 0:
            c = sess.run(cost, feed_dict={X: train_X, Y:train_Y})
        

    
    training_cost = sess.run(cost, feed_dict={X: train_X, Y: train_Y})
   

    #Graphic display
    plt.plot(train_X, train_Y, 'ro', label='Original data')
    plt.plot(train_X, sess.run(W) * train_X + sess.run(b), label='Fitted line')
    plt.legend()
    plt.show()

In [ ]:
#Regression result

In [100]:
A = train_X
Y = train_Y
b = np.ones(2888)
A = np.insert(A, 0, values=b, axis=1)
A

array([[ 1.   ,  0.566,  0.016, ..., -5.101, -2.608, -3.508],
       [ 1.   ,  0.968,  0.437, ...,  0.364, -0.335, -0.73 ],
       [ 1.   ,  1.013,  0.568, ...,  0.364,  0.765, -0.589],
       ...,
       [ 1.   , -0.394, -0.721, ..., -0.349,  0.951,  0.748],
       [ 1.   , -0.219, -0.282, ..., -0.23 , -0.301,  0.555],
       [ 1.   ,  0.368,  0.38 , ..., -0.19 , -0.567,  0.388]])

In [101]:
P=A.T.dot(A)
P.shape[1]



39

In [106]:
P1 = A.T.dot(Y)
P1.shape[0]

39

In [107]:
P2 = np.matrix(P)
P3 = P2.I
P3

matrix([[ 4.87476738e-03, -4.08818373e-04,  1.32226188e-03, ...,
         -4.14049962e-05,  8.87200845e-04, -5.41064320e-04],
        [-4.08818373e-04,  7.07537428e-03, -2.11104057e-03, ...,
         -1.09787194e-04,  2.72931325e-04,  1.17836062e-03],
        [ 1.32226188e-03, -2.11104057e-03,  6.12415974e-03, ...,
          3.32922544e-05,  1.22315510e-04,  3.50073292e-05],
        ...,
        [-4.14049962e-05, -1.09787194e-04,  3.32922544e-05, ...,
          8.53884457e-04, -4.83670664e-05, -3.98634092e-05],
        [ 8.87200845e-04,  2.72931325e-04,  1.22315510e-04, ...,
         -4.83670664e-05,  3.83685756e-03,  1.69107707e-04],
        [-5.41064320e-04,  1.17836062e-03,  3.50073292e-05, ...,
         -3.98634092e-05,  1.69107707e-04,  2.29283095e-03]])

In [108]:
P3.shape[0]
P3.shape[1]

39

In [109]:
P_P = P3.dot(P1)
P_P #最终答案

matrix([[-2.95298891e-01],
        [ 3.39984136e-01],
        [ 1.82328624e-01],
        [ 1.56182650e-01],
        [ 1.21810255e-01],
        [ 4.07653881e-02],
        [-1.15603963e-01],
        [ 1.57657729e-01],
        [-1.86641878e-01],
        [-2.05483543e-01],
        [ 2.89446090e-02],
        [ 3.33821020e-01],
        [ 5.03179152e-02],
        [ 9.54043547e-02],
        [-1.22600795e-02],
        [ 5.59908355e-02],
        [ 7.43159948e-03],
        [ 3.95533227e-02],
        [ 9.67770624e-02],
        [ 1.28621491e-02],
        [ 2.08644137e-02],
        [ 1.19738736e-02],
        [-9.11091787e-03],
        [ 1.64321647e-02],
        [ 1.73664239e-02],
        [-4.23665915e-02],
        [-3.11785776e-02],
        [ 2.70310389e-02],
        [ 1.12854767e+00],
        [-1.03158344e-02],
        [-4.34551764e-02],
        [ 1.76426825e-02],
        [-3.27015921e-04],
        [-8.93709650e-03],
        [ 1.90000877e-02],
        [-6.47370788e-03],
        [-1.81432704e-02],
 

In [110]:
df_test = pd.read_table(r'E:\tianchisaialibaba\zengqisai/zhengqi_test.txt')
df_test = pd.DataFrame(df_test)
df_test.to_csv(r'E:\tianchisaiali baba\zengqisai/zhengqi_test1.csv')

In [123]:
df_test =  pd.read_csv(r'E:\tianchisaialibaba\zengqisai//zhengqi_test1.csv')
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1925 entries, 0 to 1924
Data columns (total 39 columns):
Unnamed: 0    1925 non-null int64
V0            1925 non-null float64
V1            1925 non-null float64
V2            1925 non-null float64
V3            1925 non-null float64
V4            1925 non-null float64
V5            1925 non-null float64
V6            1925 non-null float64
V7            1925 non-null float64
V8            1925 non-null float64
V9            1925 non-null float64
V10           1925 non-null float64
V11           1925 non-null float64
V12           1925 non-null float64
V13           1925 non-null float64
V14           1925 non-null float64
V15           1925 non-null float64
V16           1925 non-null float64
V17           1925 non-null float64
V18           1925 non-null float64
V19           1925 non-null float64
V20           1925 non-null float64
V21           1925 non-null float64
V22           1925 non-null float64
V23           1925 non-null flo

In [125]:
data_test  = df_test.iloc[0:1925,1:39]
data_test1 = data_test.values
c = np.ones(1925)
data_test1 = np.insert(data_test1, 0, values=c, axis=1)
data_test1 

array([[ 1.   ,  0.368,  0.38 , ..., -0.19 , -0.567,  0.388],
       [ 1.   ,  0.148,  0.489, ...,  0.008, -0.294,  0.104],
       [ 1.   , -0.166, -0.062, ...,  0.008,  0.373,  0.569],
       ...,
       [ 1.   , -2.615, -3.564, ..., -1.537, -2.544,  1.612],
       [ 1.   , -2.661, -3.646, ..., -1.537, -2.549,  1.431],
       [ 1.   , -2.321, -3.037, ..., -1.537, -1.123,  1.988]])

In [129]:
test = data_test1.dot(P_P)
test

matrix([[ 0.26825457],
        [ 0.2600059 ],
        [-0.06905626],
        ...,
        [-3.53171707],
        [-3.48378753],
        [-2.74290238]])

In [128]:
print(A.dot(P_P))

[[ 0.76398145]
 [ 0.67803817]
 [ 0.70086211]
 ...
 [-0.44291443]
 [-0.07163421]
 [ 0.26825457]]


In [130]:
D = data_test1.T.dot(data_test1)
D

array([[ 1925.      ,  -354.978   ,  -161.531   , ...,  -571.523   ,
          -89.069   ,   376.79    ],
       [ -354.978   ,  2281.989756,  2038.046237, ...,   344.656555,
          612.788001, -1004.525101],
       [ -161.531   ,  2038.046237,  2243.891957, ...,   383.613558,
          618.284117, -1093.719356],
       ...,
       [ -571.523   ,   344.656555,   383.613558, ...,  1894.764311,
          417.865572,  -370.111848],
       [  -89.069   ,   612.788001,   618.284117, ...,   417.865572,
         2088.539919,   -75.669492],
       [  376.79    , -1004.525101, -1093.719356, ...,  -370.111848,
          -75.669492,  1775.964076]])

In [132]:
D1 = data_test1.T
D1

array([[ 1.   ,  1.   ,  1.   , ...,  1.   ,  1.   ,  1.   ],
       [ 0.368,  0.148, -0.166, ..., -2.615, -2.661, -2.321],
       [ 0.38 ,  0.489, -0.062, ..., -3.564, -3.646, -3.037],
       ...,
       [-0.19 ,  0.008,  0.008, ..., -1.537, -1.537, -1.537],
       [-0.567, -0.294,  0.373, ..., -2.544, -2.549, -1.123],
       [ 0.388,  0.104,  0.569, ...,  1.612,  1.431,  1.988]])

In [133]:
D1 = np.matrix(D1)
D2 = D1.I
D2

matrix([[ 4.06299666e-03,  7.94987235e-04, -6.02960833e-04, ...,
         -7.54437277e-05, -4.18591972e-04,  8.24112643e-04],
        [ 2.97125603e-03,  5.73716300e-05,  1.46197389e-03, ...,
          3.58180974e-04, -3.36454128e-04,  4.88205886e-04],
        [ 2.78462456e-03,  1.50064446e-04, -1.23167169e-03, ...,
          1.68114150e-04,  2.41627339e-04,  4.03787790e-04],
        ...,
        [ 3.25114789e-03, -7.06229766e-04,  1.11765398e-03, ...,
         -1.38919395e-04, -1.38621173e-03,  4.76802562e-05],
        [ 5.22026374e-03, -1.03972907e-03, -2.61726633e-04, ...,
          6.56204161e-05, -2.34535272e-03, -8.65491203e-04],
        [ 2.12496182e-03, -3.14406506e-03,  1.23602829e-03, ...,
         -6.06064329e-04, -5.46091032e-03, -2.02923855e-03]])

In [144]:
D3 = D2.dot(D)
D3 = D3.dot(P_P)
D3.shape

(1925, 1)

In [145]:
#D4 = np.delete(D3, 0, axis=1)
#D4

In [146]:
df3 = pd.DataFrame(D3)
df3

0
0     0.268255
1     0.260006
2    -0.069056
3     0.091568
4     0.271411
5     0.198774
6    -0.135067
7     0.235455
8    -0.066026
9     0.287399
10   -0.572560
11   -0.552412
12   -0.332498
13    0.094081
14   -0.087246
15    0.030504
16    0.267872
17    0.387482
18    0.378997
19    0.711955
20    0.673678
21    0.715632
22    0.889099
23    0.976790
24    0.921621
25    0.806247
26    1.010550
27    0.556117
28    0.431058
29    0.305053
...        ...
1895 -0.332681
1896 -0.332062
1897 -1.412013
1898 -0.640526
1899 -0.568795
1900 -0.910581
1901 -0.238976
1902 -0.857653
1903 -0.898016
1904 -0.389575
1905  0.380984
1906  0.615638
1907  0.582893
1908  0.431230
1909  0.701283
1910  0.171945
1911 -0.363582
1912 -0.431357
1913 -0.443199
1914 -0.876928
1915 -0.175799
1916  0.083861
1917  0.087122
1918 -0.630869
1919 -0.703020
1920 -2.780034
1921 -4.094155
1922 -3.531717
1923 -3.483788
1924 -2.742902

[1925 rows x 1 columns]

In [151]:

df3.to_csv(r'E:\tianchisaialibaba\zengqisai/test_4.txt', index=False)

In [6]:
import tensorflow
import os
import time
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from tqdm import tqdm
import math
from sklearn.model_selection import train_test_split
from sklearn import metrics

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation, CuDNNGRU, Conv1D
from keras.layers import Bidirectional, GlobalMaxPool1D
from keras.models import Model
from keras import initializers, regularizers, constraints, optimizers, layers

Using TensorFlow backend.


In [7]:
df = pd.read_table(r'E:\tianchisaialibaba\zengqisai/zhengqi_train.txt')
df = pd.DataFrame(df)
df.to_csv(r'E:\tianchisaialibaba\zengqisai/zhengqi_train1.csv')
df1 = pd.read_table(r'E:\tianchisaialibaba\zengqisai/test_1.txt')
df1 = pd.DataFrame(df)
df1.to_csv(r'E:\tianchisaialibaba\zengqisai/test_5.csv')

In [8]:
train_df  =  pd.read_csv(r'E:\tianchisaialibaba\zengqisai/zhengqi_train1.csv')
test_df  =   pd.read_csv(r'E:\tianchisaialibaba\zengqisai/zhengqi_test1.csv')
print("Train shape : ",train_df.shape)
print("Test shape : ",test_df.shape)
train_df .head()


Train shape :  (2888, 40)
Test shape :  (1925, 39)


Unnamed: 0     V0     V1     V2     V3     V4     V5     V6     V7     V8  \
0           0  0.566  0.016 -0.143  0.407  0.452 -0.901 -1.812 -2.360 -0.436   
1           1  0.968  0.437  0.066  0.566  0.194 -0.893 -1.566 -2.360  0.332   
2           2  1.013  0.568  0.235  0.370  0.112 -0.797 -1.367 -2.360  0.396   
3           3  0.733  0.368  0.283  0.165  0.599 -0.679 -1.200 -2.086  0.403   
4           4  0.684  0.638  0.260  0.209  0.337 -0.454 -1.073 -2.086  0.314   

    ...      V29    V30    V31    V32    V33    V34    V35    V36    V37  \
0   ...    0.136  0.109 -0.615  0.327 -4.627 -4.789 -5.101 -2.608 -3.508   
1   ...   -0.128  0.124  0.032  0.600 -0.843  0.160  0.364 -0.335 -0.730   
2   ...   -0.009  0.361  0.277 -0.116 -0.843  0.160  0.364  0.765 -0.589   
3   ...    0.015  0.417  0.279  0.603 -0.843 -0.065  0.364  0.333 -0.112   
4   ...    0.183  1.078  0.328  0.418 -0.843 -0.215  0.364 -0.280 -0.028   

   target  
0   0.175  
1   0.676  
2   0.633  
3   0.206  
4   0.384  

[5 rows x 40 columns]

In [9]:
train_df, val_df = train_test_split(train_df, test_size=0.1, random_state=2018)


In [10]:
embed_size = 30 # how big is each word vector
max_features = 2888 # how many unique words to use (i.e num rows in embedding vector)
maxlen = 38 # max number of words in a question to use

In [11]:
inp = Input(shape=(maxlen,))
x = Embedding(max_features, embed_size)(inp)
x = Bidirectional(CuDNNGRU(64, return_sequences=True))(x)
x = GlobalMaxPool1D()(x)
x = Dense(16, activation="relu")(x)
x = Dropout(0.1)(x)
x = Dense(1, activation="sigmoid")(x)
model = Model(inputs=inp, outputs=x)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 38)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 38, 30)            86640     
_________________________________________________________________
bidirectional_1 (Bidirection (None, 38, 128)           36864     
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 16)                2064      
_________________________________________________________________
dropout_1 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
Total para

In [17]:
train_X = train_df.iloc[:,1:39]
print(train_X.shape)

(2599, 38)


In [18]:
train_X.head()

V0     V1     V2     V3     V4     V5     V6     V7     V8     V9  \
1495  0.688  0.702  0.390 -0.153  0.644 -0.469  0.321  0.413  1.487  0.042   
2751  0.881  0.723  0.464 -0.225  0.425 -0.090  0.143  0.169  0.907  0.042   
1220  1.067  1.080  0.737  0.461  0.888 -0.670  0.055 -0.024  0.965 -1.252   
1655  0.305  0.175 -0.778 -0.148 -0.360 -0.102  0.748  1.099  0.049  0.042   
1651 -0.479 -0.419 -1.214 -0.440 -0.001  0.013  0.812  1.221 -0.612  0.042   

      ...      V28    V29    V30    V31    V32    V33    V34    V35    V36  \
1495  ...   -0.451  1.074 -0.806  1.045 -0.890 -0.843  0.160  0.364  0.337   
2751  ...    1.488  0.831  0.017  0.914 -0.411 -0.785  0.015  0.364  0.156   
1220  ...    0.738  1.628 -0.031  1.210  0.022 -0.785  0.273  0.364  0.541   
1655  ...   -0.455 -0.219 -0.136 -0.084 -0.218  0.075  0.104  0.364  0.237   
1651  ...    1.291 -0.034  0.190 -0.413  0.144  0.075  0.160  0.364 -0.486   

        V37  
1495  0.591  
2751 -0.281  
1220  0.117  
1655 -0.736  
1651  0.873  

[5 rows x 38 columns]

In [60]:

val_X = val_df[['V0','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17','V18','V19','V20','V21','V22','V23','V24','V25','V26','V27','V28','V29','V30','V31','V32','V33','V34','V35','V36','V37',]].values
test_X = test_df[['V0','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17','V18','V19','V20','V21','V22','V23','V24','V25','V26','V27','V28','V29','V30','V31','V32','V33','V34','V35','V36','V37',]].values
train_y = train_df['target'].values
val_y = val_df['target'].values
print(train_X.shape)
print(val_y.shape)

(2339, 38)
(260,)


In [64]:
## Train the model 
model.fit(train_X, train_y, batch_size=128, epochs=2, validation_data=(val_X, val_y))

Train on 2339 samples, validate on 260 samples
Epoch 1/2
2339/2339 [==============================] - ETA: 2:13 - loss: 0.6957 - acc: 0.0000e+0 - ETA: 39s - loss: 0.6864 - acc: 0.0000e+0 - ETA: 20s - loss: 0.6782 - acc: 0.0000e+ - ETA: 12s - loss: 0.6707 - acc: 0.0000e+ - ETA: 8s - loss: 0.6635 - acc: 0.0000e+00 - ETA: 5s - loss: 0.6570 - acc: 0.0000e+0 - ETA: 3s - loss: 0.6496 - acc: 0.0000e+0 - ETA: 1s - loss: 0.6403 - acc: 0.0000e+0 - ETA: 0s - loss: 0.6325 - acc: 0.0000e+0 - 8s 4ms/step - loss: 0.6292 - acc: 0.0000e+00 - val_loss: 0.5446 - val_acc: 0.0000e+00
Epoch 2/2
2339/2339 [==============================] - ETA: 0s - loss: 0.6135 - acc: 0.0000e+0 - ETA: 0s - loss: 0.5396 - acc: 0.0000e+0 - ETA: 0s - loss: 0.4605 - acc: 0.0000e+0 - ETA: 0s - loss: 0.4515 - acc: 0.0000e+0 - ETA: 0s - loss: 0.4546 - acc: 0.0000e+0 - ETA: 0s - loss: 0.4433 - acc: 0.0000e+0 - ETA: 0s - loss: 0.4463 - acc: 0.0000e+0 - ETA: 0s - loss: 0.4363 - acc: 0.0000e+0 - ETA: 0s - loss: 0.4338 - acc: 0.0000e+0